### ISSUE TITLE
Github helpers to create or check repositories 

### ISSUE THREAD

**Issue by FlavioAandres** [FlavioAandres/daily-cli#12]

**Comment by FlavioAandres** [comment]
![imagen](https://user-images.githubusercontent.com/42990423/95276898-10401200-0812-11eb-92bc-3f9f1c3be634.png)

@clouby hey, i think you can help us here with the DX, please check this pr. 

@AndresMorelos what do you think about only showing the main information like Name, created_at, language...?

**Comment by AndresMorelos** [comment]
@FlavioAandres Sure, I can let the additional information to the flag `--extended`.

Also, is there any additional information that will be needed for the table? I mean, do you want only the Name, created_at & language?

**Comment by FlavioAandres** [comment]
Mmmm... its your call, i just say it because of developer UX to reduce the colimns in the table, my suggestion is: 
- Name
- Created At 
- Languge 

I like the idea of  `--extended` flag 👍🏼

**Comment by AndresMorelos** [comment]
@FlavioAandres I uploaded the commit with that change.
