### ISSUE TITLE
Automatize versioning with github actions 

### ISSUE THREAD

**Issue by FlavioAandres** [FlavioAandres/daily-cli#13]
We can automatize the npm publishing using github actions once the package.json has been updated in the version field

**Comment by CristianJDelRio** [comment]
Wanna take a look to this issue.

**Comment by FlavioAandres** [comment]
@CristianJDelRio @clouby hey guys, take a look to this PR https://github.com/FlavioAandres/daily-cli/pull/22

if you want to test it locally install docker and `act` to your system (if you've windows i recommend you use wsl2 to run this) more info here: 

https://github.com/nektos/act
