### ISSUE TITLE
Fast path -> daily-cli goto <project_name>

### ISSUE THREAD

**Issue by FlavioAPareja** [FlavioAandres/daily-cli#2]
add a helper to save the most common routes of your project

**Comment by AndresMorelos** [comment]
@FlavioAandres could you please describe a little bit more this feature?

**Comment by FlavioAPareja** [comment]
@AndresMorelos i really was thinking this feature for all the monorepos that normally we have, ex: 

```
MonoRepo
  - Service 1 
  - Service 2 
  - Service 3 
  - scripts 
   - script_1 
   - script_2  
```

So I could use the command `daily-cli to-path script_1` and this should locate you in the folder that you want to. 

the name `to-path` is the first that I thought for this command, feel free to use another one
