### ISSUE TITLE
[BUG] : Health incidents doesn't show

### ISSUE THREAD

**Issue by AndresMorelos** [FlavioAandres/daily-cli#23]
**Describe the bug**
When I ran the health action for a service that has some issues the incidents doesn't show, and return an error of a missing variable `ora not found`.

**To Reproduce**
1. Execute the command `daily-cli health -s github`

**Expected behavior**
If the service has incidents they will be enumerated.

**Desktop (please complete the following information):**
 - OS: MacOs
 - CLI Version 0.0.5

**Additional context**
I looked at the code and the ora package is not referenced.

![image](https://user-images.githubusercontent.com/6563162/96058916-23766180-0e52-11eb-8c21-5587080fb9cf.png)
![image](https://user-images.githubusercontent.com/6563162/96058935-2d986000-0e52-11eb-8c89-38b0446fcdf6.png)

**Comment by FlavioAandres** [comment]
@AndresMorelos this only occurs when we've incidents reported?? 

![image](https://user-images.githubusercontent.com/42990423/96060301-be246f80-0e55-11eb-9b69-6fe184a54980.png)
@clouby i think you can take a look here! :D

**Comment by clouby** [comment]
@FlavioAandres Sure, i'll be in charge about this issue 😅

**Comment by clouby** [comment]
@FlavioAandres Could you please review the recent PR related with this issue, thanks 😄
