### ISSUE TITLE
AWS Account directory -> Allows adding more than 1 user in AWS and change it according the name 

### ISSUE THREAD

**Issue by FlavioAPareja** [FlavioAandres/daily-cli#3]
something like 

`$ daily-cli aws-accounts add --key="keyhere" --secret="secret-here" --name="aws-test"`
`$ daily-cli aws-accounts to --name aws-test`

**Comment by AndresMorelos** [comment]
hey @FlavioAPareja maybe you wanna see this information on where the AWS credentials are saved.

https://docs.aws.amazon.com/powershell/latest/userguide/specifying-your-aws-credentials.html#specifying-your-aws-credentials-store 

https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-shared.html

to manage profiles by the name. 

@FlavioAandres Do you have any contribution lineament? 

FYI: https://www.npmjs.com/package/manage-aws-credentials

**Comment by AndresMorelos** [comment]
@FlavioAPareja could you please review my PR for this issue?

**Comment by FlavioAandres** [comment]
Hey about the `to` functionality i know directly it doesnot work, but i've found a way,  we will have saved all our profiles, when the user wants to update the cli account, we can update the `default` profile using the following code and the aws-cli will take the new default once executed: 

```js
AWSCredentials.edit_profile('default', {
    new_name: 'default',
    access_key: 'AKIA1233489493',
    secret_access_key:'ABC123231989jka',
    cli_timestamp_format: "none"
});
```

so, we can read the profile previously saved and update the default with it, does this makes sense for you?

**Comment by AndresMorelos** [comment]
@FlavioAandres Yes, that's a valid workaround, I implemented the `to` functionality.
